### ISSUE TITLE
can i change the margin of the title 

### ISSUE THREAD

**Issue by Zinubett** [ma7moud3osman/easy_stepper#11]
can i change the margin of the title like this 
![exemple](https://user-images.githubusercontent.com/78502127/234566168-680cc31b-e671-44a5-8cf8-a71c5e004594.PNG)

**Comment by Maclaon** [comment]
hi， buddy， can u give me a example of this widget? i am a fresh man!

**Comment by Zinubett** [comment]
EasyStepper(
                activeStep: activeStep,
                lineLength: 100,
                lineType: LineType.normal,
                stepBorderRadius: 100,
                borderThickness: 2,
                internalPadding: 10,
                stepRadius: 28,
                defaultLineColor: Colors.grey,
                finishedStepBorderColor: Colors.red.shade900,
                finishedStepTextColor: Colors.red.shade900,
                finishedLineColor: Colors.red.shade900,
                finishedStepBackgroundColor: Colors.red.shade900,
                activeStepTextColor: Colors.red,
                alignment: Alignment.topCenter,
                activeStepBackgroundColor: Colors.red,
                activeStepBorderColor: Colors.red,
                showLoadingAnimation: false,
                steps: [
                  for (var i = 0; i < snapShout.data!.length; i++)
                    EasyStep(
                        customStep: ClipRRect(
                          borderRadius: BorderRadius.circular(15),
                          child: Opacity(
                            opacity: activeStep >= 0 ? 1 : 0.3,
                            child: Text('${i + 1}'),
                          ),
                        ),
                        lineText:
                            '${snapShout.data![i].min}/${snapShout.data![i].max}',
                        title: '${snapShout.data![i].title}'),
                 
                ],
                onStepReached: (index) => setState(() => activeStep = index),
              ),

**Comment by Maclaon** [comment]
> this is my code :
> 
> EasyStepper( activeStep: activeStep, lineLength: 100, lineType: LineType.normal, stepBorderRadius: 100, borderThickness: 2, internalPadding: 10, stepRadius: 28, defaultLineColor: Colors.grey, finishedStepBorderColor: Colors.red.shade900, finishedStepTextColor: Colors.red.shade900, finishedLineColor: Colors.red.shade900, finishedStepBackgroundColor: Colors.red.shade900, activeStepTextColor: Colors.red, alignment: Alignment.topCenter, activeStepBackgroundColor: Colors.red, activeStepBorderColor: Colors.red, showLoadingAnimation: false, steps: [ for (var i = 0; i < snapShout.data!.length; i++) EasyStep( customStep: ClipRRect( borderRadius: BorderRadius.circular(15), child: Opacity( opacity: activeStep >= 0 ? 1 : 0.3, child: Text('${i + 1}'), ), ), lineText: '${snapShout.data![i].min}/${snapShout.data![i].max}', title: '${snapShout.data![i].title}'),
> 
> ```
>             ],
>             onStepReached: (index) => setState(() => activeStep = index),
>           ),
> ```

each `EasyStep ` content in its child ?

**Comment by Zinubett** [comment]
I don't understand your question

**Comment by Maclaon** [comment]
> I don't understand your question

sorry, buddy, my mistake!

**Comment by ma7moud3osman** [comment]
Hello @Zinubett ,
You can use `customTitle` or `customLineWidget` to add your own widgets with a lot of customization to achieve this design 
```
     customTitle: Container(
                          margin: const EdgeInsets.symmetric(horizontal: 50),
                          child: Text(
                            'Custom Title $i',
                            textAlign: TextAlign.center,
                            maxLines: 3,
                          ),
                        ),
```
