### ISSUE TITLE
Can i disable/enable specific easystep?

### ISSUE THREAD

**Issue by thfr69** [ma7moud3osman/easy_stepper#12]
e.g. is there a way to disable the easy_steps not yet reached, despite "steppingEnabled = true" of the easy_stepper?
I want to navigate from one step to another only with a prev or next button unless a step has already been reached

**Comment by ma7moud3osman** [comment]
Hi @thfr69 ,
Thank you for your participation.
In the previous version there is no way to enable/disable a specific step, but it was added in the new version `0.5.1` by changing the `enabled`  property  available for each `EasyStep` separately.
