### ISSUE TITLE
Add lineThickness

### ISSUE THREAD

**Issue by mjablecnik** [ma7moud3osman/easy_stepper#13]
I see that I can set `borderThickness` or `lineLength` but `lineThickness` I'm missing.

**Comment by ma7moud3osman** [comment]
Hi @mjablecnik , 
You can change line thickness by setting the `lineDotRadius` property which responsible for the  dot radius if `lineType` set to `LineType.dotted` or the line thickness if the `lineType` is set to  `LineType.normal` in this case

**Comment by mjablecnik** [comment]
@ma7moud3osman Yes, it works, thank you ;)

I am using `lineType` as `LineType.normal` and it is very hard to understand that `lineDotRadius` can change the thickness of the line.
Do you think that you can rename it to `lineThickness` which will set the thickness of dotted and normal lines?
I think that it can be more user friendly and more understandable.. :)

**Comment by ma7moud3osman** [comment]
Yes it's more readable to be 'lineThickness' instead of 'lineDotRadius' of course, I will rename it in the next release.
Thank you @mjablecnik
