### ISSUE TITLE
Error: Couldn't find constructor 'EdgeInsetsDirectional.symmetric'.

### ISSUE THREAD

**Issue by kshatriyaArjunDeveloper** [ma7moud3osman/easy_stepper#14]
When I use this widget it has a class field padding with by default  EdgeInsetsDirectional.symmetric(horizontal: 10, vertical: 10). But compiler shows there is no way to give EdgeInsetsDirectional.symmetric value with symmetric constructor.

**Comment by ma7moud3osman** [comment]
Hi @kshatriyaArjunDeveloper ,
Thank you for your feedback, but can you please clarify your problem further? Padding works correctly and there is no issue with the compiler with me.

**Comment by fajarainul** [comment]
I am currently facing this issue. My colleague add this easy_stepper on our project, after I pull the latest code from git then  doing `flutter pub get` and run my project, this issue occurred. What is wrong with my code?
I use flutter 3.3.10.

**Comment by yomohamed47** [comment]
> I am currently facing this issue. My colleague add this easy_stepper on our project, after I pull the latest code from git then doing `flutter pub get` and run my project, this issue occurred. What is wrong with my code? I use flutter 3.3.10.

Same For me using versoin of package 0.6.0 and can't upgrade it because the lottie package either
