### ISSUE TITLE
Large title not showing correctly in vertical stepper.

### ISSUE THREAD

**Issue by basemosama** [ma7moud3osman/easy_stepper#19]
When trying to show a large title in vertical stepper the title isn't centered and is shown moving to the left of the step as below.
<img src="https://user-images.githubusercontent.com/19964129/239023066-4ca59251-10ad-45c8-a358-ddb58f5c2171.jpg"  height ="300">
This happens when trying to set vertical stepper line length to a small length which if i used in horizontal stepper will have conflict with next step.
When using bigger line length it works as expected as below.
<img src="https://user-images.githubusercontent.com/19964129/239021935-c2e01393-17db-4e8f-bd4e-4d91c70f5f04.jpg" height ="300">
I think title position should depend on line legnth only on horizontal stepper. 

Also, If we can have a content widget next to each step will be great.
Thanks.

**Comment by ma7moud3osman** [comment]
Hi @basemosama 
Thanks for your contribution 
We Fix large title not showing correctly in the vertical stepper & it not depending on the line length any more you can check it work as expected in v.0.6.0 .
We will add content widget for horizontal & vertical stepper & other more features in the future releases .
best regards, 
Mahmoud
