### ISSUE TITLE
How to make the length of the stepper full.

### ISSUE THREAD

**Issue by seamoonpandey** [ma7moud3osman/easy_stepper#20]

**Comment by ma7moud3osman** [comment]
Hello @seamoonpandey 
Thank you for your contribution.
we add `fitWidth` property in the new release v.0.6.0 & it should work as expected when `disableScroll = true`.
regards.

**Comment by synarda** [comment]
this problem still exists

**Comment by seamoonpandey** [comment]
> this problem still exists. even though you do what the package wants, if you give a value of “stepRadius” it only takes that much space.
yup this problem still persists but you can make a workaround by doing a lots of mediaquery based spacing logics 😓

**Comment by synarda** [comment]
For my project, the problem disappeared when I removed the “stepRadius” value, but it should also work when the “stepRadius” value is entered. I think there will be an update to the package after the last update in flutter and dart, these problems should be fixed there.
