### ISSUE TITLE
Wrap EasyStepper with Scrollbar on web

### ISSUE THREAD

**Issue by SeriousMonk** [ma7moud3osman/easy_stepper#23]
Hi, awesome package!

I would like to wrap the EasyStepper widget with a ScrollBar widget so that the stepper can be easily scrolled on web too. Currently it can be swiped to scroll, but on web this is not a very intuitive behavior.

It would be nice if this could be integrated, otherwise if you could add the possibility to pass a ScrollController to the EasyStepper so that I can wrap the stepper with a ScrollBar manually :)

**Comment by ma7moud3osman** [comment]
Hi @SeriousMonk ,
Thank you for your feedback ,

We override the default scroll behavior and add mouse to the `dragDevices` and now stepper can be scrolled on web or desktop apps.
also we add the `scrollbar` for web & desktop and you can control it whether to show or hide it.

best regards,
Mahmoud Osman.
