### ISSUE TITLE
Is it possible to draw a line halfway between the current step and the next step?

### ISSUE THREAD

**Issue by lx8s8** [ma7moud3osman/easy_stepper#28]
![image](https://github.com/ma7moud3osman/easy_stepper/assets/2274385/1f354c02-df67-42df-b861-278f06cfe5b5)

**Comment by ma7moud3osman** [comment]
Hi @lx8s8 
Now you can achieve this by using `progress` & `progressColor` inside  `LineStyle` class 
Best Regards,
Mahmoud Osman
