### ISSUE TITLE
Want to remove hand pointer when hovering over steps.

### ISSUE THREAD

**Issue by WillCordova** [ma7moud3osman/easy_stepper#29]
Hello, I want the hover-over steps to be disabled since my logic has no need for it. I thought that (steppingEnabled: false) would fix it however it doesn't work. I was wondering if you could provide a way to disable it.

**Comment by ma7moud3osman** [comment]
Hello @WillCordova ,

You can disable tapping on steps & remove hover by set `enableStepTapping: false` , not `steppingEnabled: false` it just prevent user from move to this step but he still can tap on it. in your case you should use `enableStepTapping`.

Thank You, 
Best Regards,
Mahmoud Osman.
