### ISSUE TITLE
It's currently impossible to set a step border type

### ISSUE THREAD

**Issue by sethgnavo** [ma7moud3osman/easy_stepper#3]
The default border of steps is dashed and there is no possibility to customize it except for changing its `borderThickness` and borderColor (unreached, active and finished).
In order to conform to different design requirements, it would be interesting to have the option to change the border type of steps.

Example:
`activeStepBorderType: BorderType.normal | BorderType.dotted`
`unreachedStepBorderType: BorderType.normal | BorderType.dotted`
`finishedStepBorderType:  BorderType.normal | BorderType.dotted`

Also, it'd be great to enable/disable the border altogether.
Example:
`showStepBorder: false`

**Comment by ma7moud3osman** [comment]
Hi Seth,

Thank you for your feedback. I'm adding it as an enhancement for the next release and will keep you posted!

Warm Regards,
Mahmoud Osman

**Comment by ma7moud3osman** [comment]
The border type feature has been added to Stepper in the latest v0.3.1 version. Please update your dependency and code. 

Regards
Mahmoud Osman
