### ISSUE TITLE
the steps text get cut when use many steps with scrolling 

### ISSUE THREAD

**Issue by BelalNayzak** [ma7moud3osman/easy_stepper#32]
I've used the package on flutter web and it works perfect. Just when I have many steps the upper text get cut like the attached image.
![Untitled](https://github.com/ma7moud3osman/easy_stepper/assets/50274195/58b48cb8-7d4a-4e47-a439-6c650dceb527)

**Comment by ma7moud3osman** [comment]
Hi @BelalNayzak ,
Sorry for the delay, I'm working on it & it will be fixed in the next release.
Thank You.

**Comment by ma7moud3osman** [comment]
It now fixed in release 0.8.2

**Comment by ma7moud3osman** [comment]
It should now fixed in release 0.8.2 

best regards,
Mahmoud Osman

**Comment by BelalNayzak** [comment]
Very well!
Thank you Mahmoud
