### ISSUE TITLE
Is  there a property to stop the `loading_animation` ?

### ISSUE THREAD

**Issue by OmarYehiaDev** [ma7moud3osman/easy_stepper#4]
I'm searching for a way to stop the loading animation inside the active step. What should I do?

**Comment by ma7moud3osman** [comment]
Hey Omar,
You can stop the loading animation for the active step by providing `activeIcon` inside the Step you want to stop the animation in it.
Hope this helps.

**Comment by OmarYehiaDev** [comment]
Thank you, it worked!
I hope if you can provide a standalone property to trigger the loading event, I think this will be much better :")

**Comment by ma7moud3osman** [comment]
Thank you for your feedback,
I'm adding it as an enhancement for the next release and will keep you posted!
