### ISSUE TITLE
Standalone property to trigger the loading event

### ISSUE THREAD

**Issue by ma7moud3osman** [ma7moud3osman/easy_stepper#5]
Thank you, it worked!
I hope if you can provide a standalone property to trigger the loading event, I think this will be much better :")

_Originally posted by @OmarYehiaDev in https://github.com/ma7moud3osman/easy_stepper/issues/4#issuecomment-1425791323_

**Comment by OmarYehiaDev** [comment]
I've added a [PR#6](https://github.com/ma7moud3osman/easy_stepper/pull/6) for this feature :")
I've tested it but you can do more tests and just merge it when everything's ready for the new release :")

**Comment by ma7moud3osman** [comment]
Added in v.0.3.2 , thanks to Omar Yehia  [PR#6](https://github.com/ma7moud3osman/easy_stepper/pull/6)
