### ISSUE TITLE
Setting title above or below step icon

### ISSUE THREAD

**Issue by AbdulazizAlnahhas** [ma7moud3osman/easy_stepper#9]
Hello 
first Thank you for this useful package 
is it possible to set title of step above the step icon like this image?
<img width="242" alt="Screen Shot 2023-04-03 at 2 55 17 PM" src="https://user-images.githubusercontent.com/29395420/229502268-00942e97-4897-4a46-95c1-82ce0297c2fc.png">

**Comment by ma7moud3osman** [comment]
Thank you @AbdulazizAlnahhas  for your feedback, 
I will working on it and add it to the next release and will keep you posted!
regards,
Mahmoud Osman

**Comment by ma7moud3osman** [comment]
Show title above or below the step icon has been added to the latest version v0.5.0. please update your dependances and code.
best regards,
Mahmoud Osman
